### ISSUE TITLE
PAT/PMT are not present at the start of a segment

### ISSUE THREAD

**Issue by htrendev** [m3u8-segmenter/m3u8-segmenter#3]
According to the HTTP live streaming draft, at the beginning of each segment there should be PMT/PAT tables. Currently m3u8-segmenter puts these tables later in the file and they also appear several times in a single segment file.

I suspect that this may be causing a problem in the iPhone simulator and in QuickTime on OSX. Sometimes in the middle of a segmented stream the video suddenly starts to play in slow motion. The same source file segmented with Apple's own mediastreamsegmenter plays just fine both in the iPhone simulator and in QuickTime.

This problem doesn't seem to affect the hardware devices (iPhones/iPads), just the QuickTime player in OSX and in iPhone simulator.

Not sure if this is indeed cased by the PAT/PMT tables, but it was the most obvious difference between the files produced by m3u8-segmenter and the ones produced by Apple's mediastreamsegmenter. Also, mediastreamsegmenter seems to put just a single copy of these tables in the beginning of a segment, while m3u8-segmenter puts them at random (probably at the same places and just as frequently as they appear in the source TS file).

HTTP Live Streaming Draft:
   "Transport Stream files MUST contain a single MPEG-2 Program.  There
   SHOULD be a Program Association Table and a Program Map Table at the
   start of each file.  A file that contains video SHOULD have at least
   one key frame and enough information to completely initialize a video
   decoder."

**Comment by johnf** [comment]
So that side of things all happens in ffmpeg land so I don't have much control. One thing I did notice though is that every file after the first one didn't have the PAT/PMT at the start of the file. I've fixed things so that it now does this at least.

Can you check if that made any difference. If that doesn't fix it I'll look into filing a bug in ffmpeg to add some extra functionality to be able to turn of the PAT/PMT creation every X packets

**Comment by htrendev** [comment]
Thanks! Unfortunately, this didn't fix the problem, but it seems that now each segment (as standalone file) starts playing immediately. Probably because now there are PAT/PMT tables in the very beginning of the file. So there is some improvement, even though it is not related to the problem.

I have also noticed that now there are several PMT tables. Here are two screenshots taken from TS analyzer running on windows for two random segments:
m3u8-segmenter with PAT/PMT fix - http://img834.imageshack.us/img834/6985/m3u8segmenter.png
apple mediastreamsegmenter - http://img849.imageshack.us/img849/7879/muediastreamsegmenter.png
Video source is the same - pcap capture of a live pre-encoded stream which I replay against apple's segmenter or m3u8-segmenter to generate the segments.

I am compiling m3u8-segmenter on ubuntu 10.04 with ffmpeg 6.1 compiled from source. I can also provide TS segment file or the pcap capture itself if that will help, but it seems indeed that this is caused by the way ffmpeg writes the TS segments. Ideally each segment should have one PAT table, followed by one PMT table, followed by the video/audio streams.

**Comment by johnf** [comment]
I'm pretty sure it is ffmpeg that is doing this. If I create a TS file directly

ffmpeg -loglevel quiet  -i big_buck_bunny.ogv -f mpegts

Then it has the same issue

johnf@zoot:~/dev/m3u8-segmenter/trunk/tests$ tsinfo moo.ts 
Reading from moo.ts
Scanning 1000 TS packets

Packet 2 is PAT
Program list:
    Program 1 -> PID 0fff (4095)

Packet 3 is PMT with PID 0fff (4095)
  Program 1, version 0, PCR PID 0100 (256)
  Program streams:
    PID 0100 ( 256) -> Stream type 02 (  2) H.262/13818-2 video (MPEG-2) or 11172-2 constrained video
    PID 0101 ( 257) -> Stream type 03 (  3) 11172-3 audio (MPEG-1)

Found 48 PAT packets and 24 PMT packets in 1000 TS packets

**Comment by htrendev** [comment]
I think there is also a problem with writing the header at the beginning of each segment. Probably the commit for this ticket needs to be reviewed. There are two problems that I've noticed:
- The first packet in every segment is still a not a PAT/PMT. PAT seems to be at packet 2 (sometimes packet 4)
- And what seems worse - it appears that the number of programs in the PAT increases by 1 every time a new segment is written

From my test stream (only the relevant parts from tsinfo output)
for segment 1 I have:
....
Packet 2 is PAT
Program list:
    Program 1 -> PID 0fff (4095)

Packet 3 is PMT with PID 0fff (4095)
....

for segment 2:
....
Packet 2 is PAT
Program list:
    Program 1 -> PID 0fff (4095)
    Program 1 -> PID 1000 (4096)
Multiple programs in PAT - using the first

Packet 3 is PMT with PID 0fff (4095)
....

for segment 3:
Packet 2 is PAT
....
Program list:
    Program 1 -> PID 0fff (4095)
    Program 1 -> PID 1000 (4096)
    Program 1 -> PID 1001 (4097)
Multiple programs in PAT - using the first

Packet 3 is PMT with PID 0fff (4095)
....

and it keeps on increasing, so potentially this will be a problem for longer input streams since the programs in the PAT can become very large numbers.

for the 19th segment for example the output is:
....
Packet 4 is PAT
Program list:
    Program 1 -> PID 0fff (4095)
    Program 1 -> PID 1000 (4096)
    Program 1 -> PID 1001 (4097)
    Program 1 -> PID 1002 (4098)
    Program 1 -> PID 1003 (4099)
    Program 1 -> PID 1004 (4100)
    Program 1 -> PID 1005 (4101)
    Program 1 -> PID 1006 (4102)
    Program 1 -> PID 1007 (4103)
    Program 1 -> PID 1008 (4104)
    Program 1 -> PID 1009 (4105)
    Program 1 -> PID 100a (4106)
    Program 1 -> PID 100b (4107)
    Program 1 -> PID 100c (4108)
    Program 1 -> PID 100d (4109)
    Program 1 -> PID 100e (4110)
    Program 1 -> PID 100f (4111)
    Program 1 -> PID 1010 (4112)
    Program 1 -> PID 1011 (4113)
Multiple programs in PAT - using the first

Packet 5 is PMT with PID 0fff (4095)
...

**Comment by htrendev** [comment]
http://gstreamer-devel.966125.n4.nabble.com/Implementing-a-MPEGTS-segmenter-what-s-the-best-approach-td3169098.html

This thread is somewhat relevant. Maybe it's too radical to even consider replacing ffmpeg with gstreamer, but it appears that gstreamer's multifilesink plugin has support for writing headers in the beginning of each segment. It seems to split segments at key frames. I couldn't find anything that mentions how to define the length of each segment, but this can always be done from within m3u8-segmenter.
